# Generated by Django 4.1.2 on 2022-10-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=80, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=240)),
            ],
        ),
    ]
